on: create
jobs:
  setup-digitalocean:
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    runs-on: ubuntu-latest
    env:
      CLIENT_DOMAIN: ${{ secrets.CLIENT_DOMAIN }}
      PUBLIC_KEY: ${{ secrets.CITI_PUBLIC_KEY }}
      FINGERPRINT: ${{ secrets.CITI_FINGERPRINT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - name: Create Project
        run: |
          doctl projects create --name ${{github.event.repository.name}} --purpose "Web Application" | awk 'NR==2{print $1}' > project_id.txt
      - name: Create Droplet
        run: |
          doctl compute droplet create ${{github.event.repository.name}} --image dokku-20-04 --region nyc1 --size s-1vcpu-1gb --ssh-keys $FINGERPRINT --wait | tee >(awk 'NR==2{print $1}' > droplet_id.txt) >(awk 'NR==2{print $3}' > droplet_ip.txt)
      - name: Assign Droplet to Project
        run: |
          doctl projects resources assign $(cat project_id.txt) --resource do:droplet:$(cat droplet_id.txt)
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan $(cat droplet_ip.txt) >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.CITI_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      - name: Setup Dokku
        run: |
          ssh root@$(cat project_ip.txt) 'CLIENT_DOMAIN=$CLIENT_DOMAIN PUBLIC_KEY=$PUBLIC_KEY bash -s' < ./setup-dokku.sh
      - name: Commit droplet IP to repo
        run: |
          git config --global user.email "citi@cin.ufpe.br"
          git config --global user.name "citiufpe"
          git add droplet_ip.txt
          git commit -m "Add droplet IP"
          git push origin main
